export const image = {
    jollof: require('../assets/images/jollof.png'),
    shawarma: require('../assets/images/shawarma.png'),
    coke:require('../assets/images/coke.jpeg'),
    hollandia: require('../assets/images/hollandia.jpeg'),
    active: require('../assets/images/active.jpeg'),
    aquafina: require('../assets/images/aquafina.png'),
    chips: require('../assets/images/chips.png'),
    semo: require('../assets/images/semo.jpeg'),
    fufu: require('../assets/images/fufu.jpeg'),
    smoothies: require('../assets/images/smoothies.png'),
    parfait: require('../assets/images/parfait.png'),
    icecream: require('../assets/images/icecream.png'),
    apple: require('../assets/images/apple.png'),
    strawberry: require('../assets/images/strawberry.png'),
    image: require('../assets/images/image.png'),
    emptybox: require('../assets/images/emptybox.png'),
    banner1: require('../assets/images/banner1.png'),
    banner2: require('../assets/images/banner2.png'),
    banner3: require('../assets/images/banner3.png'),
    banner4: require('../assets/images/banner4.png'),
    banner5: require('../assets/images/banner5.png'),
    banner6: require('../assets/images/banner6.png'),
    banner7: require('../assets/images/banner7.png'),
    
}